#!/usr/bin/evn python
# -*- coding: utf-8 -*-

CONFIG = {
    "INTERVAL_SECONDS": 180,
    "TWITTER_CONSUMER_KEY": "",
    "TWITTER_CONSUMER_SECRET": "",
    "TWITTER_ACCESS_TOKEN_KEY": "",
    "TWITTER_ACCESS_TOKEN_SECRET": "",
    "INSTAGRAM_CLIENT_ID": "",
    "INSTAGRAM_CLIENT_SECRET": "",
    "INSTAGRAM_ACCESS_TOKEN": "",
}

